### ISSUE TITLE
章节3.5里面提到的用wget下载国内重要网站名单的问题

### ISSUE THREAD

**Issue by kenshinji** [softwaredownload/openwrt-fanqiang#13]
按照书里的：
    `wget -4 --no-check-certificate -O　/etc/dnsmasq.d/accelerated-domains.china.conf　https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf`

运行后只会提示`wget: missing URL`, 另外wget的参数`-4`是什么意思？

**Comment by softwaredownload** [comment]
运行命令：
wget --help 
-4,  --inet4-only              connect only to IPv4 addresses

**Comment by softwaredownload** [comment]
里面有全角空格的缘故，已经修复：

    wget -4 --no-check-certificate -O /etc/dnsmasq.d/accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
