### ISSUE TITLE
抱歉，该视频仅限中国大陆地区播放，请您观看其他视频！

### ISSUE THREAD

**Issue by dayifutian** [softwaredownload/openwrt-fanqiang#15]
访问http://www.tudou.com/albumplay/YL80fDOEmL0/dAljnGQepGY.html时出现提示不能播放。
youku.com也有个别视频出现同样提示，地址没记下来。
路由wndr4300，不会编译，直接下载来刷的，看了下文件accelerated-domains.china.conf文件里面有tudou.com的记录啊。谢谢。

**Comment by softwaredownload** [comment]
accelerated-domains.china.conf 里的域名解析和流量都走国内。
测试你的链接，可以 播放

**Comment by dayifutian** [comment]
是啊，accelerated-domains.china.conf 里面有tudou.com 和youku.com的记录，但还是被土豆网认为是国外地址了。
我用chrome浏览器，google搜索迪亚哥动画片，从google直接跳转到土豆，http://www.tudou.com/albumplay/YL80fDOEmL0/dAljnGQepGY.html
我刷回官方固件，停用ss后访问土豆没问题了。

这种问题能提供下排查思路吗？ 谢谢

**Comment by softwaredownload** [comment]
从百度搜索试试

**Comment by softwaredownload** [comment]
应该是从 google搜索跳转引起的，和翻墙固件无关。

google搜索是走翻墙通道的（也就是国外IP)，tudou.com不允许国外IP观看视频，有时把跳转来源的国外IP当作访客的本机IP了。
