### ISSUE TITLE
经多次摸索，终于成功，有一个问题问楼主。

### ISSUE THREAD

**Issue by PJovy** [softwaredownload/openwrt-fanqiang#18]
请问路由器openwrt里面的SS配置可以修改端口和密码这些吗？如果可以，那么只要修改路由器shadowsocks.json，然后对应的VPS服务端修改好就行了吗？

**Comment by softwaredownload** [comment]
如果你没有修改本地端口和tunnel端口，是这样的。

**Comment by PJovy** [comment]
这个版本要求服务器端支持udp转发吗？还有，请问一下你编译的这个固件中ss支持chacha20加密吗？

**Comment by softwaredownload** [comment]
服务端要求 udp转发。 ss不支持chacha20。用 bf-cfb就很好，不需要用chacha20

**Comment by PJovy** [comment]
好的，刚试了一下，还是按照你原来的配置才能上。请问AP模式可以用来直接插上上级路由，然后就能翻墙了吗？这个路由器自动识别模式的么

**Comment by softwaredownload** [comment]
不是自动识别的，详细看教程。AP模式稍微复杂些

**Comment by PJovy** [comment]
嗯，好的，感谢你的付出，能让我们小白可以方便使用。
我感觉这个路由不是很强大，不知道你有没有什么好的推荐呢？好刷，稳定，速度快的

**Comment by softwaredownload** [comment]
DIR505这个路由就是可以作为备用。WNDR4300不错。
