### ISSUE TITLE
3.5节我记得之前有chmod +x shadowsocks-firewall,最新版好像没了

### ISSUE THREAD

**Issue by billzhuang** [softwaredownload/openwrt-fanqiang#20]
不需要么？

顺便请教个问题，现在都是在nat表里做的ss，如果我路由器本身需要翻墙该怎办？
比如我想在路由器里配国外的ddns，比如duckdns，iptables不太会……

**Comment by softwaredownload** [comment]
本教程就是给路由器翻墙的，然后接入设备就自动翻墙
