### ISSUE TITLE
支持多个SS服务器

### ISSUE THREAD

**Issue by auflute** [softwaredownload/openwrt-fanqiang#22]
请问如果要支持多个SS服务器，以负载均衡的方式连接，或者一个断了自动连接下一个，最好是能自动连接速度最快的服务器 ，像shadowsocks的windows客户端的自带功能一样，不知道是否支持？

因为我买的ss服务，往往提供多个服务器，有时一个服务器不稳定时最好可以方便切换到另一个。如果每次去路由器里改配置，那就很麻烦了。

**Comment by softwaredownload** [comment]
可能不支持多SS服务器以负载均衡的方式连接

**Comment by helloljq** [comment]
额  我还没有到支持多个服务器这一步  我买的ss都是提供域名形式的服务器地址，而不是IP形式。  目前好像只支持IP地址？

**Comment by softwaredownload** [comment]
如果可以直接用域名代替IP地址，那么翻墙过程多了查域名IP这一步，网速就会降低。因此，即使可以也不可取。

你可以查出域名对应的IP，尝试一下是否可以使用该IP
