### ISSUE TITLE
请问如何关闭路由器上的UDP转发功能？

### ISSUE THREAD

**Issue by jack338c** [softwaredownload/openwrt-fanqiang#23]
service_start /usr/bin/ss-tunnel -b 0.0.0.0 -c /etc/shadowsocks.json -l 3210 -L 8.8.8.8:53 -u(把最后这个-u去掉是不是算关闭路由器上的udp了,多谢!﻿

因为发现同样节点手机上的ANDRIOD-SS访问网络速度比路由快，手机上没启用UPD转发

**Comment by softwaredownload** [comment]
关闭UDP转发会导致被墙域名解析可能被污染
