### ISSUE TITLE
请问如何更新固件到您现在发布的最新版本

### ISSUE THREAD

**Issue by PJovy** [softwaredownload/openwrt-fanqiang#24]
RT

**Comment by softwaredownload** [comment]
方法1：
复制配置文件到路由器，并修改相关文件，这需要对教程比较比较熟悉。我的一个旧路由器就是这样升级的

方法：刷新固件

**Comment by PJovy** [comment]
现在最新的固件是什么时候的

2016年3月18日星期五，Kig Eca <notifications@github.com> 写道：

**Comment by softwaredownload** [comment]
没有问题，一般不用更新固件，更新配置文件就可以了。新固件的信息页面上有标示
