### ISSUE TITLE
经常性出现代理连接中断的现象

### ISSUE THREAD

**Issue by PJovy** [softwaredownload/openwrt-fanqiang#26]
已经检查VPS上SS服务没有问题，路由器端，ss-redir  ss-tunnel  dnsmasq 进程都在，解决办法只能重启路由器，不知道是什么原因

**Comment by softwaredownload** [comment]
有二种可能：
1. 进程在，但是进程假死了
2. 被干扰

重启后正常，一般是第一种情况

**Comment by PJovy** [comment]
查看了，进程都在，应该是进程假死
这是什么原因呢？
不过重启比较麻烦，有没有什么解决办法呢
2016年3月20日星期日，Kig Eca <notifications@github.com> 写道：

**Comment by softwaredownload** [comment]
把中国IP走白名单改成亚洲IP走白名单会好些。匹配中国IP次数太频繁会导致资源不足

**Comment by PJovy** [comment]
噢，不太会弄这个，请问具体如何设置呢

2016-03-20 10:42 GMT+08:00 Kig Eca <notifications@github.com>:

**Comment by softwaredownload** [comment]
下面文件就是：
https://github.com/softwaredownload/openwrt-fanqiang/blob/master/openwrt/dir505/usr/bin/shadowsocks-firewall
