### ISSUE TITLE
请问在shadowsocks-firewall文件里加上什么规则可以使亚洲某个被墙的网站可以访问

### ISSUE THREAD

**Issue by jack338c** [softwaredownload/openwrt-fanqiang#27]
路由器是DLIN505，没用chinadns_chnroute.txt文件，请帮解决下，谢谢！

**Comment by softwaredownload** [comment]
1. 这个网站的域名不能在accelerated-domains.china.conf 文件中
2. 查出这个网站的IP地址，然后把 shadowsocks-firewall ， Ignore Asia IP address系列命令中包含该IP所在行注释掉，使该IP系列地址的流量走翻墙通道

**Comment by jack338c** [comment]
谢谢前辈指教！IT WORKS!
