### ISSUE TITLE
使用的4300，看了您的教程，操作了，越操作越糊涂。

### ISSUE THREAD

**Issue by pooy** [softwaredownload/openwrt-fanqiang#29]
只需要讲git clone下来的包拽到openwrt里面，然后配置就可以了吗？

还是说先opkg install  shadowsocks\*  ?

**Comment by softwaredownload** [comment]
> git clone下来的包拽到openwrt里面，然后配置就可以了

**Comment by zwzhou** [comment]
iptables 那里可以用 ipset 来做的，可以省不少事
