### ISSUE TITLE
Image Configuration时未预先 set target

### ISSUE THREAD

**Issue by aixlx** [softwaredownload/openwrt-fanqiang#30]
4.1节中，
>先编译要用到的工具和库
>make prereq && make tools/install && make toolchain/install

按照官方的推荐，应先 `run make menuconfig and set target`，否则之后编译不能成功。

ref: https://wiki.openwrt.org/doc/howto/build

**Comment by softwaredownload** [comment]
上次编译时，照教程顺序操作没有发现问题。可能现在有所改变了，能不能详细记录你的操作过程，然后提交个 Pull Request?
