### ISSUE TITLE
IPtables 配置问题请教

### ISSUE THREAD

**Issue by jun1an** [softwaredownload/openwrt-fanqiang#33]
#for hulu.com
iptables -t nat -A SHADOWSOCKS -p tcp --dport 1935 -j REDIRECT --to-ports 7654
iptables -t nat -A SHADOWSOCKS -p udp --dport 1935 -j REDIRECT --to-ports 7654
防火墙配置这一段有问题需要请教,这是将1935端口转发到本地的7654吗,如果是,1935端口是在哪里配置的,谢谢,
另外,按照教程配置后无法上网,一直提示找不到nds,

**Comment by softwaredownload** [comment]
这段可以注释掉，用不到了
