### ISSUE TITLE
按照教程设置后，境外IP都无法访问，请问是哪里出了问题？

### ISSUE THREAD

**Issue by just4somefun** [softwaredownload/openwrt-fanqiang#34]
ss服务端是正常的，用ss-local测试翻墙正常

但是按照教程设置后，境内IP正常，境外IP都不能访问，不知道是哪里出了问题，求指导。

**Comment by zhaojunmo** [comment]
我也遇过，原因是服务器没有开放对应的UDP端口，你看看是不是这个问题。

**Comment by chuzirui** [comment]
有可能是DNS 污染的问题
