### ISSUE TITLE
偶然出现国内网站不能访问，墙外网站正常, 重启/etc/init.d/shadowsocks服务之后正常

### ISSUE THREAD

**Issue by zhaojunmo** [softwaredownload/openwrt-fanqiang#35]
已经出现过几次，突然发现国内网站不能访问，但是通过ss访问的墙外网站就没有问题。Ping国内网站没有问题，不知道是哪方面的原因。

**Comment by tefiszx** [comment]
我最近也出现了题主的问题。国内的不能连接，不只是域名解析的问题还是连接被丢弃的问题。请问楼上的你开了路由器的广告屏蔽功能吗?翻墙路由的前端或后端是否还接驳了其他的网络设备？

**Comment by tefiszx** [comment]
晕死，三天之内已经两次出现这样的故障。重启路由器或 /etc/init.d/ shadowsocks restart后故障消失，但不定期又会出现只能连墙外，墙内连不上的情况。ssh连入openwrt，ping baidu.com nslookup baidu.com都是正常的。请问如何继续排查？

**Comment by softwaredownload** [comment]
启用中国IP不走翻墙通道及广告屏蔽，如果路由器硬件不够好，短时间打开较多网页会导致路由器软件失去响应，这时往往需要重启路由器解决

中国IP列表条目很多，打开一个网页通常会有很多请求，每个请求都要和中国IP地址列表进行匹配，这会比较消耗资源。建议普通规格的路由器不要用中国IP列表，而是启用亚洲IP地址列表不走翻墙通道

**Comment by Danny8090** [comment]
如果无法访问国内网站，在网络防火墙自定义规则添加这条规则：
iptables -t nat -I POSTROUTING -j MASQUERADE
