### ISSUE TITLE
iptables可以对域名进行转发吗？

### ISSUE THREAD

**Issue by tefiszx** [softwaredownload/openwrt-fanqiang#41]
我使用的google的云服务器，vps的ip是不固定的，但是域名固定。
在配置文件中又如下一句

>  Ignore your shadowsocks server's addresses
>  It's very IMPORTANT, just be careful.
> 
> iptables -t nat -A SHADOWSOCKS -d 1.0.9.8 -j RETURN

上面这一句配置 是否可以改为如下写法
`iptables -t nat -A SHADOWSOCKS -s --string “googletw.xyz ” --algo bm -j RETURN`
怎样查看openwrt的iptabels是否支持string 模块？

**Comment by softwaredownload** [comment]
建议使用固定IP的VPS
