### ISSUE TITLE
ss-redir全局代理问题

### ISSUE THREAD

**Issue by sharpsec** [softwaredownload/openwrt-fanqiang#43]
按照教程中策略，利用ss-redir 和 iptables 的功能，实现了翻墙，目前本机IP显示国外的，但是国外网站还是访问不了，国内网站正常访问，从vps抓包看，国外网站的交互握手发生了timeout，导致FIN，而国内正常握手和数据交互，请问这是什么原因啊，困扰了很长时间

**Comment by softwaredownload** [comment]
按照教程中提示的内容逐项检查，详细测试和记录

**Comment by tefiszx** [comment]
重点检查shadowssocks-firewall文件里的iptable命令和/etc/chinadns_route.txt文件的内容是否健全
