### ISSUE TITLE
---

### ISSUE THREAD

**Issue by tefiszx** [softwaredownload/openwrt-fanqiang#45]
---

**Comment by tefiszx** [comment]
已经找到youtube安卓客户端3秒断流的解决办法。方法如下：1、修改/etc/init.d/shadowsocks文件，把ss-redir 加-u参数启动；2、修改/usr/bin/shadowsocks-firewall文件，在防火墙规则中增加一条iptables规则，将443端口的upd重定向到shadowsocks监听的端口即可

**Comment by tefiszx** [comment]
请本项目的创建者把该方法合并到项目中去。

**Comment by softwaredownload** [comment]
感谢提供详细的信息

我在iPhone测试了 YouTube客户端，目前没有发现断流。我这里不方便测试你提出的改进

如果方便的话，能不能发个 Pull Request，我再把你的修改合并到教程中

具体步骤如下：

Fork 本项目 ( https://github.com/softwaredownload/openwrt-fanqiang/fork )
创建你的分支 (git checkout -b my-new-feature)
提交你的改进 (git commit -am 'Add some feature')
Push到你的分支 (git push origin my-new-feature)
到github.com 创建 Pull Request

**Comment by softwaredownload** [comment]
已经更新，具体修改请见下面的提交，如有问题请反馈：

https://github.com/softwaredownload/openwrt-fanqiang/commit/28ce4f638c01447d40490c2c084d2e2dc2a5fc93

**Comment by softwaredownload** [comment]
完全的 udp 转发还未实现，todo之一
