### ISSUE TITLE
现在还能用嘛？

### ISSUE THREAD

**Issue by zewenhs** [softwaredownload/openwrt-fanqiang#49]
现在VPN 查的更严了， 请问现在还能用吗？

**Comment by cornrn** [comment]
可以用

**Comment by softwaredownload** [comment]
一直在用

**Comment by barce-zhao** [comment]
那么大家有共享的服务器或帐号吗？

2018年4月4日 19:40，"Kig Eca" <notifications@github.com>写道：

**Comment by softwaredownload** [comment]
用自己的，可以永久稳定使用，用得舒心。网上可能有共享的，但是不稳定，什么时候失效要又要去找
