### ISSUE TITLE
ss+openwrt14.07打开facebook、twitter、google不正常

### ISSUE THREAD

**Issue by abv76** [softwaredownload/openwrt-fanqiang#5]
使用shadowsocks 的win客户端连接服务器时打开上面网页都正常，
但在openwrt路由器上使用shadowsocks+GFWlist时无法打开
是否DNS受污染缘故？

**Comment by ripples-alive** [comment]
是否 DNS 污染的话，你本地 nslookup 看看 IP 呗

**Comment by softwaredownload** [comment]
查看ss-server是否已经启动并且带有 -u启动参数
	ps ax | grep ss-server
	
如果启动正常，返回结果类似如下：
	
	/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -a root -u -f /var/run/shadowsocks-libev/shadowsocks-libev.pid
	
注意其中有-u。如果shadowsocks客户端启用了udp relay, 而服务端启动时不带-u参数，翻墙自然就失败了。

如果服务端启动里带　-u 翻墙还有问题，请检查其他设置
