### ISSUE TITLE
是否可以反复执行/usr/bin/shadowsocks-firewall？

### ISSUE THREAD

**Issue by shanehou** [softwaredownload/openwrt-fanqiang#50]
反复执行`/usr/bin/shadowsocks-firewall`是否会使iptables规则变得越来越长（有重复）？使用`iptables -L`并没有看到加入的规则。

路由器是WR2543，直接使用了带shadowsocks的预编译固件

**Comment by softwaredownload** [comment]
多执行几次没有关系的
