### ISSUE TITLE
支持刷OpenWrt路由器是可以直接使用那里提供的固件，window下可以登录管理页面直接刷吗？还是要在Linux下自己编译然后再刷

### ISSUE THREAD

**Issue by huanyuan** [softwaredownload/openwrt-fanqiang#57]

**Comment by softwaredownload** [comment]
支持刷OpenWrt路由器是可以直接使用那里提供的固件，一般情况下Window下可以登录管理页面直接刷。刷好后还要按照教程进行一些设置才可以翻墙

自己编译固件后再刷是为了把设置预编译进去，这样刷好后就直接可以用了或者再经少量设置就可以用了
